header:
  version: 17

machine: genericarm64
distro: poky

target: core-image-sato

repos:
  meta-custom:
  meta-everest:
    url: https://github.com/EVerest/meta-everest.git
    commit: c9ac56a0c7aa00e2155d1808bec286f8a2800481
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded.git
    commit: e8fd97d86af86cdcc5a6eb3f301cbaf6a2084943
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-gnome:
  meta-arm:
    url: https://git.yoctoproject.org/meta-arm.git
    commit: 8e0f8af90fefb03f08cd2228cde7a89902a6b37c
    layers:
      meta-arm:
      meta-arm-toolchain:
      meta-arm-bsp:
  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi.git
    commit: 48452445d779b0f69bf1ead12b3850d50eb8920d
  poky:
    url: https://git.yoctoproject.org/poky.git
    commit: ac257900c33754957b2696529682029d997a8f28
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

local_conf_header:
  wifi: |
    DISTRO_FEATURES:append = " wifi"
  packages: |
    CORE_IMAGE_EXTRA_INSTALL += " connman-gnome everest-core mosquitto less vim htop wireshark"
  fstypes: |
    IMAGE_FSTYPES += " wic.vdi"
  password: |
    INHERIT += "extrausers"
    EXTRA_USERS_PARAMS = "useradd aria; \
                          usermod -p '\$1\$x8be6haF\$uKuamZOYwxUMqnwpfsC2x0' aria; \
                          usermod -a -G sudo aria;"

