header:
  version: 17

machine: genericarm64
distro: poky

target: core-image-sato

repos:
  meta-custom:
  meta-everest:
    url: https://github.com/EVerest/meta-everest.git
    commit: 15bc7703d2c58b521e02c0135c1f308fcdad3bd0
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded.git
    commit: e8fd97d86af86cdcc5a6eb3f301cbaf6a2084943
    layers:
      meta-oe:
      meta-python:
      meta-networking:
  meta-arm:
    url: https://git.yoctoproject.org/meta-arm.git
    commit: 8e0f8af90fefb03f08cd2228cde7a89902a6b37c
    layers:
      meta-arm:
      meta-arm-toolchain:
      meta-arm-bsp:
  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi.git
    commit: 48452445d779b0f69bf1ead12b3850d50eb8920d
  poky:
    url: https://git.yoctoproject.org/poky.git
    commit: ac257900c33754957b2696529682029d997a8f28
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

local_conf_header:
  fstypes: |
    IMAGE_FSTYPES += " wic.vdi"
  password: |
    INHERIT += "extrausers"
    EXTRA_USERS_PARAMS = "usermod -p '\$1\$aS1Ntik4\$q.OegCxDok9DQ1mvtLHvG.' root; \
                          useradd aria; \
                          usermod -p '\$1\$x8be6haF\$uKuamZOYwxUMqnwpfsC2x0' aria; \
                          usermod -a -G sudo aria;"
