header:
  version: 17
  includes:
    - yeti-yak.yml

machine: raspberrypi4-64
distro: poky

target: yeti-yak-image

repos:
  meta-custom:
  meta-yeti-yak:
    url: https://github.com/PionixPublic/yeti-yak-sdk
    branch: release/kirkstone/2024.9.0 
    patches:
      config:
        repo: meta-custom
        path: everest-config.patch
    layers:
      meta-yeti-yak:
  meta-everest:
    url: https://github.com/EVerest/meta-everest.git
    branch: release/kirkstone/2024.9.0
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded.git
    branch: kirkstone
    patches:
      nodejs:
        repo: meta-custom
        path: 0001-upgrade-nodejs-to-maybe-fix-build.patch
    layers:
      meta-oe:
      meta-python:
      meta-networking:
  meta-arm:
    url: https://git.yoctoproject.org/meta-arm.git
    branch: kirkstone
    layers:
      meta-arm:
      meta-arm-toolchain:
      meta-arm-bsp:
  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi.git
    branch: kirkstone
  poky:
    url: https://git.yoctoproject.org/poky.git
    commit: 7e87dc422d972e0dc98372318fcdc63a76347d16
    patches:
      elfutils:
        repo: meta-custom
        path: elfutils-no-werror.patch
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

local_conf_header:
  disk-space: |
    IMAGE_ROOTFS_EXTRA_SPACE:append = " + 4000000"
  password: |
    INHERIT += "extrausers"
    EXTRA_USERS_PARAMS = "usermod -p '\$1\$aS1Ntik4\$q.OegCxDok9DQ1mvtLHvG.' root; \
                          useradd aria; \
                          usermod -p '\$1\$x8be6haF\$uKuamZOYwxUMqnwpfsC2x0' aria; \
                          usermod -a -G sudo aria;"
